changelog:
  exclude:
    labels:
      - release
  categories:
    - title: New features
      labels:
        - new feature
    - title: Bug fixes
      labels:
        - bug
    - title: Other changes
      labels:
        - "*"