version: "3"
services:
  fhir-server:
    image: "docker-registry.it.csiro.au/clinsight/fhir-server:${CLINSIGHT_VERSION}"
    ports:
      - 8080:8080
    environment:
      CLINSIGHT_TERMINOLOGY_SERVER_URL: http://ontoserver:8080/fhir
  ontoserver:
    image: "docker-registry.it.csiro.au/clinsight/ontoserver:${CLINSIGHT_VERSION}"
    depends_on:
      - ontodb
    environment:
      - atom.syndication.feedLocation=https://r4.ontoserver.csiro.au/synd/syndication.xml
      - ontoserver.feature.eclFilters=true
      - ontoserver.feature.msgaEnabled=true
      - ontoserver.fhir.batch.queueSize=20000
      - ontoserver.fhir.too.costly.threshold=200000
      - spring.datasource.url=jdbc:postgresql://ontodb/postgres
      - JAVA_OPTS=-Xmx24G
      - ONTOSERVER_INSECURE=true
    volumes:
      - ontofiles:/var/onto
  ontodb:
    image: postgres:10
    networks:
      - clinsight
    volumes:
      - ontodb:/var/lib/postgresql/data
volumes:
  ontofiles:
    driver: local
  ontodb:
    driver: local
