version: 2
jobs:
  test_server: &build
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Test server
          command: mvn test -pl fhir-server -am
      - store_test_results: &encoders_reports
          path: encoders/target/surefire-reports
      - store_test_results: &server_reports
          path: fhir-server/target/surefire-reports
      - store_artifacts:
          <<: *encoders_reports
      - store_artifacts:
          <<: *server_reports
  push_server:
    <<: *build
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build server image
          command: mvn package -pl fhir-server -am -DskipShade -DfhirServerDockerRepo=$FHIR_SERVER_DOCKER_REPO
      - run:
          name: Tag and push server image
          command: mvn dockerfile:tag@tag-major dockerfile:tag@tag-latest dockerfile:push@push-version dockerfile:push@push-major dockerfile:push@push-latest -pl fhir-server -DfhirServerDockerRepo=$FHIR_SERVER_DOCKER_REPO -Ddockerfile.username=$DOCKER_USERNAME -Ddockerfile.password=$DOCKER_PASSWORD
      - store_test_results:
          <<: *encoders_reports
      - store_test_results:
          <<: *server_reports
      - store_artifacts:
          <<: *encoders_reports
      - store_artifacts:
          <<: *server_reports
  test_site: &build_site
    docker:
      - image: circleci/ruby:2.6.3
    steps:
      - checkout
      - run:
          name: Build site
          command: cd site && bundle && bundle exec jekyll build
  push_site:
    <<: *build_site
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Login to Docker
          command: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run:
          name: Build and push site image
          command: cd site && bundle && bundle exec jekyll build && docker build . -t aehrc/pathling-site && docker push aehrc/pathling-site
workflows:
  version: 2
  build_deploy:
    jobs:
      - test_server:
          filters:
            branches:
              ignore: master
      - push_server:
          filters:
            branches:
              only: master
      - test_site:
          filters:
            branches:
              ignore: master
      - push_site:
          filters:
            branches:
              only: master
