version: 2
jobs:
  build: &build
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build server
          command: mvn install -pl fhir-server -am -DskipTests -DskipITs -DskipShade -Ddockerfile.skip
  deploy:
    <<: *build
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and push Docker image
          command: mvn deploy -pl fhir-server -am -Dmaven.deploy.skip -DskipTests -DskipITs -DskipShade -DfhirServerDockerRepo=$FHIR_SERVER_DOCKER_REPO -Ddockerfile.username=$DOCKER_USERNAME -Ddockerfile.password=$DOCKER_PASSWORD
  build_site: &build_site
    docker:
      - image: circleci/ruby:2.6.3
    steps:
      - checkout
      - run:
          name: Build site
          command: cd site && bundle && bundle exec jekyll build
  deploy_site:
    <<: *build_site
    steps:
      - setup_remote_docker
      - run:
          name: Login to Docker
          command: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run:
          name: Build and push site image
          command: cd site && docker build . -t aehrc/pathling-site && docker push aehrc/pathling-site
workflows:
  version: 2
  build_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
#          filters:
#            branches:
#              only: master
      - build_site
      - deploy_site:
          requires:
            - build_site
#          filters:
#            branches:
#              only: master
