version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
  build:
    commands:
      # Build just the FHIR server, and its dependencies.
      - mvn install -pl fhir-server -am
cache:
  paths:
    - '/root/.m2/**/*'
