version: 0.2

env:
  exported-variables:
    - DOCKER_REGISTRY
phases:
  install:
    runtime-versions:
      java: openjdk8
      nodejs: 12
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Building Docker images...
      - mvn deploy -pl fhir-server,ui -am -Dmaven.deploy.skip -DskipITs -DdockerRegistry=$DOCKER_REGISTRY
cache:
  paths:
    - '/root/.m2/**/*'
