version: "3"
services:
  fhir-loader:
    image: docker-registry.it.csiro.au/clinsight/fhir-loader
    network_mode: host
    environment:
      CLINSIGHT_SPARK_MASTER_URL: spark://hb-15-cdc001.it.csiro.au:7077
      CLINSIGHT_WAREHOUSE_DIRECTORY: hdfs://hb-15-cdc001.it.csiro.au:8020/warehouse
      CLINSIGHT_METASTORE_URL: jdbc:postgresql://hb-15-cdc001.it.csiro.au/clinsight_metastore
      CLINSIGHT_METASTORE_USER: postgres
      CLINSIGHT_EXECUTOR_MEMORY: 6g
      CLINSIGHT_JSON_BUNDLES_PATH: hdfs://hb-15-cdc001.it.csiro.au:8020/staging/synthea/1k_20190408_3
