apiVersion: v2
name: pathling
description: A Helm chart for Pathling Server
icon: https://raw.githubusercontent.com/aehrc/pathling/main/media/logo-icon-colour-detail.svg
type: application
version: 1.0.0
