version: "3"
services:
  fhir-server:
    image: docker-registry.it.csiro.au/clinsight/fhir-server
    network_mode: host
    depends_on:
      - ontoserver
    environment:
      CLINSIGHT_SPARK_MASTER_URL: spark://hb-15-cdc001.it.csiro.au:7077
      CLINSIGHT_WAREHOUSE_DIRECTORY: hdfs://hb-15-cdc001.it.csiro.au:8020/warehouse
      CLINSIGHT_METASTORE_URL: jdbc:postgresql://hb-15-cdc001.it.csiro.au/clinsight_metastore
      CLINSIGHT_METASTORE_USER: postgres
      CLINSIGHT_DATABASE_NAME: clinsight
      CLINSIGHT_EXECUTOR_MEMORY: 6g
      CLINSIGHT_TERMINOLOGY_SERVER_URL: http://hb-15-cdc001.it.csiro.au:4066/fhir
    restart: unless-stopped
  ui:
    image: docker-registry.it.csiro.au/clinsight/ui
    network_mode: host
    restart: unless-stopped
    ports:
      - 8899:80
    environment:
      CLINSIGHT_FHIR_SERVER: http://clinsight.it.csiro.au:8090/fhir
  ontoserver:
    image: docker-registry.it.csiro.au/clinsight/ontoserver:5.4.0-SNAPSHOT
    network_mode: host
    depends_on:
      - ontodb
    environment:
      - server.port=4066
      - spring.datasource.url=jdbc:postgresql://hb-15-cdc001.it.csiro.au:5433/postgres
      # - atom.syndication.feedLocation=https://ontoserver.csiro.au/synd/syndication.xml
      - authentication.oauth.endpoint.client_id.0=66611fd3-74cb-49de-97f1-662397094b81
      - authentication.oauth.endpoint.client_secret.0=ecba0d30-b674-45f8-9661-8fbedc3092c0
      - ontoserver.feature.eclFilters=true
      - ontoserver.feature.msgaEnabled=true
      - ontoserver.fhir.batch.queueSize=20000
      - ontoserver.fhir.too.costly.threshold=200000
      - JAVA_OPTS=-Xmx24G
      - ONTOSERVER_INSECURE=true
    volumes:
      - ontofiles:/var/onto
    restart: unless-stopped
  ontodb:
    image: postgres:10
    network_mode: host
    command: postgres -p 5433
    volumes:
      - ontodb:/var/lib/postgresql/data
    restart: unless-stopped
  master:
    image: docker-registry.it.csiro.au/clinsight/spark-master
    network_mode: host
    environment:
      SPARK_MASTER_HOST: hb-15-cdc001.it.csiro.au
      SPARK_MASTER_OPTS: "-Dspark.ui.reverseProxy=true -Dspark.ui.reverseProxyUrl=http://hb-15-cdc001.it.csiro.au:8080"
      SPARK_DAEMON_MEMORY: 8g
    restart: unless-stopped
  worker:
    image: docker-registry.it.csiro.au/clinsight/spark-worker
    network_mode: host
    command: bash -c "/opt/spark/sbin/start-slave.sh --host hb-15-cdc001.it.csiro.au spark://hb-15-cdc001.it.csiro.au:7077" 2>&1
    environment:
      SPARK_WORKER_CORES: 6
      SPARK_WORKER_MEMORY: 28g
      SPARK_WORKER_OPTS: "-Dspark.shuffle.service.enabled=true"
      HIVE_SITE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hb-15-cdc001.it.csiro.au/clinsight_metastore"
    restart: unless-stopped
  metastore:
    image: postgres:10
    network_mode: host
    environment:
      POSTGRES_DB: clinsight_metastore
    volumes:
      - metastore:/var/lib/postgresql/data
    restart: unless-stopped
  notebook:
    image: docker-registry.it.csiro.au/clinsight/notebook
    network_mode: host
    environment:
      SPARK_DRIVER_HOST: hb-15-cdc001.it.csiro.au
      SPARK_DRIVER_PORT: 52000
      SPARK_DRIVER_MEMORY: 8g
    volumes:
      - notebooks:/home/jovyan/work
      - ${PWD}/hive-site.xml:/usr/local/spark/conf/hive-site.xml
    restart: unless-stopped
  namenode:
    image: uhopper/hadoop-namenode:2.7.2
    network_mode: host
    environment:
      CLUSTER_NAME: clinsight
      CORE_CONF_fs_default_name: hdfs://hb-15-cdc001.it.csiro.au:8020
      HDFS_CONF_dfs_permissions_enabled: "false"
      HDFS_CONF_dfs_client_use_datanode_hostname: "true"
      HDFS_CONF_dfs_datanode_use_datanode_hostname: "true"
      HDFS_CONF_dfs_namenode_datanode_registration_ip___hostname___check: "false"
      HDFS_CONF_dfs_replication: "2"
    volumes:
      - /mnt/cl_warehouse_1/hadoop/name:/hadoop/dfs/name
    restart: unless-stopped
  datanode:
    image: uhopper/hadoop-datanode:2.7.2
    network_mode: host
    environment:
      CORE_CONF_fs_default_name: hdfs://hb-15-cdc001.it.csiro.au:8020
      HDFS_CONF_dfs_permissions_enabled: "false"
      HDFS_CONF_dfs_datanode_hostname: hb-15-cdc001.it.csiro.au
    volumes:
      - /mnt/cl_warehouse_1/hadoop/data:/hadoop/dfs/data
    restart: unless-stopped
volumes:
  ontodb:
    driver: local
  ontofiles:
    driver: local
  metastore:
    driver: local
  notebooks:
    driver: local
