apiVersion: v1
entries:
  pathling:
  - apiVersion: v2
    created: "2023-12-18T00:31:23.723993981Z"
    description: A Helm chart for Pathling Server
    digest: 73c19cdeb6fbc3b7de3dd9cb622c946e486570bf9401695048fbeea34a2fe2c6
    icon: https://raw.githubusercontent.com/aehrc/pathling/main/media/logo-icon-colour-detail.svg
    keywords:
    - spark
    - analytics
    - standards
    - fhir
    - terminology
    maintainers:
    - email: John.Grimes@csiro.au
      name: John Grimes
    name: pathling
    sources:
    - https://github.com/aehrc/pathling
    type: application
    urls:
    - https://pathling.csiro.au/helm/pathling-1.0.0.tgz
    version: 1.0.0
generated: "2023-12-18T00:31:23.723371248Z"
