apiVersion: v1
entries:
  pathling:
  - apiVersion: v2
    created: "2023-12-17T23:47:51.212799314Z"
    description: A Helm chart for Pathling Server
    digest: 0879360cf1bbf60a3aed92c42c6787a33f6a86a07f16ac50080199183f827ccd
    icon: https://raw.githubusercontent.com/aehrc/pathling/main/media/logo-icon-colour-detail.svg
    keywords:
    - spark
    - analytics
    - standards
    - fhir
    - terminology
    maintainers:
    - email: John.Grimes@csiro.au
      name: John Grimes
    name: pathling
    sources:
    - https://github.com/aehrc/pathling
    type: application
    urls:
    - https://pathling.csiro.au/helm/pathling-1.0.0.tgz
    version: 1.0.0
generated: "2023-12-17T23:47:51.212286896Z"
