apiVersion: v1
entries:
  pathling:
  - apiVersion: v2
    created: "2024-05-21T07:30:32.600596784Z"
    description: A Helm chart for Pathling Server
    digest: 3c9188baf4d794119c72e7fa252cf3cbb0e9ed988a1df422fbac28d929752ddc
    icon: https://raw.githubusercontent.com/aehrc/pathling/main/media/logo-icon-colour-detail.svg
    keywords:
    - spark
    - analytics
    - standards
    - fhir
    - terminology
    maintainers:
    - email: John.Grimes@csiro.au
      name: John Grimes
    name: pathling
    sources:
    - https://github.com/aehrc/pathling
    type: application
    urls:
    - https://pathling.csiro.au/helm/pathling-1.0.1.tgz
    version: 1.0.1
generated: "2024-05-21T07:30:32.599989003Z"
