apiVersion: v1
entries:
  pathling:
  - apiVersion: v2
    created: "2023-12-18T06:12:36.774495664Z"
    description: A Helm chart for Pathling Server
    digest: faa55b48f183b25991286b7e5014946fb2b69ab6f7ecf42d4843012e43c07f12
    icon: https://raw.githubusercontent.com/aehrc/pathling/main/media/logo-icon-colour-detail.svg
    keywords:
    - spark
    - analytics
    - standards
    - fhir
    - terminology
    maintainers:
    - email: John.Grimes@csiro.au
      name: John Grimes
    name: pathling
    sources:
    - https://github.com/aehrc/pathling
    type: application
    urls:
    - https://pathling.csiro.au/helm/pathling-1.0.0.tgz
    version: 1.0.0
generated: "2023-12-18T06:12:36.773962912Z"
