apiVersion: v1
entries:
  pathling:
  - apiVersion: v2
    created: "2024-05-22T04:15:10.668295192Z"
    description: A Helm chart for Pathling Server
    digest: 093cc66997dca971cb8971ba007f44b45fb3dc99bc582e231f0a6439e2969142
    icon: https://raw.githubusercontent.com/aehrc/pathling/main/media/logo-icon-colour-detail.svg
    keywords:
    - spark
    - analytics
    - standards
    - fhir
    - terminology
    maintainers:
    - email: John.Grimes@csiro.au
      name: John Grimes
    name: pathling
    sources:
    - https://github.com/aehrc/pathling
    type: application
    urls:
    - https://pathling.csiro.au/helm/pathling-1.0.2.tgz
    version: 1.0.2
generated: "2024-05-22T04:15:10.667755447Z"
