apiVersion: v1
entries:
  pathling:
  - apiVersion: v2
    created: "2023-12-11T06:59:50.711616541Z"
    description: A Helm chart for Pathling Server
    digest: bd805d23a7296363bef10504aa5361fc98d6872b0addcce98d182545e00a706c
    icon: https://raw.githubusercontent.com/aehrc/pathling/main/media/logo-icon-colour-detail.svg
    keywords:
    - spark
    - analytics
    - standards
    - fhir
    - terminology
    maintainers:
    - email: John.Grimes@csiro.au
      name: John Grimes
    name: pathling
    sources:
    - https://github.com/aehrc/pathling
    type: application
    urls:
    - https://pathling.csiro.au/helm/pathling-1.0.0.tgz
    version: 1.0.0
generated: "2023-12-11T06:59:50.711081824Z"
