apiVersion: v1
entries:
  pathling:
  - apiVersion: v2
    created: "2023-12-11T12:17:28.725009839Z"
    description: A Helm chart for Pathling Server
    digest: bd95468a8e5506d433808c48260a4d26d983d9f10e36302844cc1749d7181f5d
    icon: https://raw.githubusercontent.com/aehrc/pathling/main/media/logo-icon-colour-detail.svg
    keywords:
    - spark
    - analytics
    - standards
    - fhir
    - terminology
    maintainers:
    - email: John.Grimes@csiro.au
      name: John Grimes
    name: pathling
    sources:
    - https://github.com/aehrc/pathling
    type: application
    urls:
    - https://pathling.csiro.au/helm/pathling-1.0.0.tgz
    version: 1.0.0
generated: "2023-12-11T12:17:28.724491283Z"
