apiVersion: v1
entries:
  pathling:
  - apiVersion: v2
    created: "2023-12-13T10:53:34.126757635Z"
    description: A Helm chart for Pathling Server
    digest: 6aaec5a3c8cd7ce2afee9ae81eb82c3fe63bad45fcf1d1d02b789796e6e30da0
    icon: https://raw.githubusercontent.com/aehrc/pathling/main/media/logo-icon-colour-detail.svg
    keywords:
    - spark
    - analytics
    - standards
    - fhir
    - terminology
    maintainers:
    - email: John.Grimes@csiro.au
      name: John Grimes
    name: pathling
    sources:
    - https://github.com/aehrc/pathling
    type: application
    urls:
    - https://pathling.csiro.au/helm/pathling-1.0.0.tgz
    version: 1.0.0
generated: "2023-12-13T10:53:34.125516095Z"
