apiVersion: v1
entries:
  pathling:
  - apiVersion: v2
    created: "2024-03-25T01:30:29.465366925Z"
    description: A Helm chart for Pathling Server
    digest: ea1134ed429d3dde5a975f6df76f1d5178088379c38eaae8784d03d76b4911c8
    icon: https://raw.githubusercontent.com/aehrc/pathling/main/media/logo-icon-colour-detail.svg
    keywords:
    - spark
    - analytics
    - standards
    - fhir
    - terminology
    maintainers:
    - email: John.Grimes@csiro.au
      name: John Grimes
    name: pathling
    sources:
    - https://github.com/aehrc/pathling
    type: application
    urls:
    - https://pathling.csiro.au/helm/pathling-1.0.0.tgz
    version: 1.0.0
generated: "2024-03-25T01:30:29.464559547Z"
