apiVersion: v1
entries:
  pathling:
  - apiVersion: v2
    created: "2023-12-12T11:17:19.14356422Z"
    description: A Helm chart for Pathling Server
    digest: 21fc7698235973cd8dded6b0256e618e5e73f6c0c2520b4b1bd353865ae4de52
    icon: https://raw.githubusercontent.com/aehrc/pathling/main/media/logo-icon-colour-detail.svg
    keywords:
    - spark
    - analytics
    - standards
    - fhir
    - terminology
    maintainers:
    - email: John.Grimes@csiro.au
      name: John Grimes
    name: pathling
    sources:
    - https://github.com/aehrc/pathling
    type: application
    urls:
    - https://pathling.csiro.au/helm/pathling-1.0.0.tgz
    version: 1.0.0
generated: "2023-12-12T11:17:19.14303858Z"
