apiVersion: v1
entries:
  pathling:
  - apiVersion: v2
    created: "2024-03-22T04:33:52.296837993Z"
    description: A Helm chart for Pathling Server
    digest: 18382d57e0e712096deb2da5872c4d45ec134b81c101ec9b7451c5750b197fde
    icon: https://raw.githubusercontent.com/aehrc/pathling/main/media/logo-icon-colour-detail.svg
    keywords:
    - spark
    - analytics
    - standards
    - fhir
    - terminology
    maintainers:
    - email: John.Grimes@csiro.au
      name: John Grimes
    name: pathling
    sources:
    - https://github.com/aehrc/pathling
    type: application
    urls:
    - https://pathling.csiro.au/helm/pathling-1.0.0.tgz
    version: 1.0.0
generated: "2024-03-22T04:33:52.2962814Z"
