apiVersion: v1
entries:
  pathling:
  - apiVersion: v2
    created: "2023-12-12T23:51:36.383515169Z"
    description: A Helm chart for Pathling Server
    digest: 8409fd690240e59643e0e7a288fba16bd1ee95eff55b0cbd92cc1ccf8c0e2688
    icon: https://raw.githubusercontent.com/aehrc/pathling/main/media/logo-icon-colour-detail.svg
    keywords:
    - spark
    - analytics
    - standards
    - fhir
    - terminology
    maintainers:
    - email: John.Grimes@csiro.au
      name: John Grimes
    name: pathling
    sources:
    - https://github.com/aehrc/pathling
    type: application
    urls:
    - https://pathling.csiro.au/helm/pathling-1.0.0.tgz
    version: 1.0.0
generated: "2023-12-12T23:51:36.38298025Z"
