apiVersion: v1
entries:
  pathling:
  - apiVersion: v2
    created: "2023-12-12T23:45:39.368978122Z"
    description: A Helm chart for Pathling Server
    digest: d05a827fff19bda1901a5f0ae73eb5f9cc9e947f61232230da70b2709e82fece
    icon: https://raw.githubusercontent.com/aehrc/pathling/main/media/logo-icon-colour-detail.svg
    keywords:
    - spark
    - analytics
    - standards
    - fhir
    - terminology
    maintainers:
    - email: John.Grimes@csiro.au
      name: John Grimes
    name: pathling
    sources:
    - https://github.com/aehrc/pathling
    type: application
    urls:
    - https://pathling.csiro.au/helm/pathling-1.0.0.tgz
    version: 1.0.0
generated: "2023-12-12T23:45:39.368422229Z"
