apiVersion: v1
entries:
  pathling:
  - apiVersion: v2
    created: "2023-12-11T01:28:43.015534183Z"
    description: A Helm chart for Pathling Server
    digest: 931d08e405856637415762925c789d7b4dafce6a0476c970fc41d81f468ccfae
    icon: https://raw.githubusercontent.com/aehrc/pathling/main/media/logo-icon-colour-detail.svg
    keywords:
    - spark
    - analytics
    - standards
    - fhir
    - terminology
    maintainers:
    - email: John.Grimes@csiro.au
      name: John Grimes
    name: pathling
    sources:
    - https://github.com/aehrc/pathling
    type: application
    urls:
    - https://pathling.csiro.au/helm/pathling-1.0.0.tgz
    version: 1.0.0
generated: "2023-12-11T01:28:43.014900343Z"
