apiVersion: v1
entries:
  pathling:
  - apiVersion: v2
    created: "2024-04-11T23:19:06.554573419Z"
    description: A Helm chart for Pathling Server
    digest: 6747dd0f9431116cdd362b7098fceb2779cfaf3d760ab4b3035868a1763bba9c
    icon: https://raw.githubusercontent.com/aehrc/pathling/main/media/logo-icon-colour-detail.svg
    keywords:
    - spark
    - analytics
    - standards
    - fhir
    - terminology
    maintainers:
    - email: John.Grimes@csiro.au
      name: John Grimes
    name: pathling
    sources:
    - https://github.com/aehrc/pathling
    type: application
    urls:
    - https://pathling.csiro.au/helm/pathling-1.0.0.tgz
    version: 1.0.0
generated: "2024-04-11T23:19:06.554017754Z"
