apiVersion: v1
entries:
  pathling:
  - apiVersion: v2
    created: "2023-12-17T08:51:19.483324167Z"
    description: A Helm chart for Pathling Server
    digest: a2b4aa06d616db68c18c44e1f0a85cff536f5395b0128fdc357d3f13dffac3e9
    icon: https://raw.githubusercontent.com/aehrc/pathling/main/media/logo-icon-colour-detail.svg
    keywords:
    - spark
    - analytics
    - standards
    - fhir
    - terminology
    maintainers:
    - email: John.Grimes@csiro.au
      name: John Grimes
    name: pathling
    sources:
    - https://github.com/aehrc/pathling
    type: application
    urls:
    - https://pathling.csiro.au/helm/pathling-1.0.0.tgz
    version: 1.0.0
generated: "2023-12-17T08:51:19.482538914Z"
