apiVersion: v1
entries:
  pathling:
  - apiVersion: v2
    created: "2023-12-14T00:22:04.427181995Z"
    description: A Helm chart for Pathling Server
    digest: bc5f33794b815965a06fddab334c1059338a6d5f196db1fc3ab876d68495fcb5
    icon: https://raw.githubusercontent.com/aehrc/pathling/main/media/logo-icon-colour-detail.svg
    keywords:
    - spark
    - analytics
    - standards
    - fhir
    - terminology
    maintainers:
    - email: John.Grimes@csiro.au
      name: John Grimes
    name: pathling
    sources:
    - https://github.com/aehrc/pathling
    type: application
    urls:
    - https://pathling.csiro.au/helm/pathling-1.0.0.tgz
    version: 1.0.0
generated: "2023-12-14T00:22:04.42658689Z"
