apiVersion: v1
entries:
  pathling:
  - apiVersion: v2
    created: "2023-12-03T08:34:49.511913565Z"
    description: A Helm chart for Pathling Server
    digest: 20324e8fa57d5fb39a126f8fff46d55b0099ba48830a47baaa2f8bf91f220de7
    icon: https://raw.githubusercontent.com/aehrc/pathling/main/media/logo-icon-colour-detail.svg
    name: pathling
    type: application
    urls:
    - https://pathling.csiro.au/helm/pathling-1.0.0.tgz
    version: 1.0.0
generated: "2023-12-03T08:34:49.511387374Z"
