apiVersion: v1
entries:
  pathling:
  - apiVersion: v2
    created: "2023-12-11T07:05:31.482736467Z"
    description: A Helm chart for Pathling Server
    digest: 47a4088de34c5a4009300e4e984908560d43fba852bf7b2590ef8082df21dd1b
    icon: https://raw.githubusercontent.com/aehrc/pathling/main/media/logo-icon-colour-detail.svg
    keywords:
    - spark
    - analytics
    - standards
    - fhir
    - terminology
    maintainers:
    - email: John.Grimes@csiro.au
      name: John Grimes
    name: pathling
    sources:
    - https://github.com/aehrc/pathling
    type: application
    urls:
    - https://pathling.csiro.au/helm/pathling-1.0.0.tgz
    version: 1.0.0
generated: "2023-12-11T07:05:31.482004962Z"
