apiVersion: v1
entries:
  pathling:
  - apiVersion: v2
    created: "2024-02-07T05:10:08.433480935Z"
    description: A Helm chart for Pathling Server
    digest: adb5bed1a6a886e4c5f98590db470ac97fc0ee61f668dbeebde490627d270451
    icon: https://raw.githubusercontent.com/aehrc/pathling/main/media/logo-icon-colour-detail.svg
    keywords:
    - spark
    - analytics
    - standards
    - fhir
    - terminology
    maintainers:
    - email: John.Grimes@csiro.au
      name: John Grimes
    name: pathling
    sources:
    - https://github.com/aehrc/pathling
    type: application
    urls:
    - https://pathling.csiro.au/helm/pathling-1.0.0.tgz
    version: 1.0.0
generated: "2024-02-07T05:10:08.432940124Z"
