apiVersion: v1
entries:
  pathling:
  - apiVersion: v2
    created: "2024-01-11T07:09:04.462784658Z"
    description: A Helm chart for Pathling Server
    digest: d65640ab830b5da41193859ca2c331d3be17d9170a23e0a5827b489acf929c78
    icon: https://raw.githubusercontent.com/aehrc/pathling/main/media/logo-icon-colour-detail.svg
    keywords:
    - spark
    - analytics
    - standards
    - fhir
    - terminology
    maintainers:
    - email: John.Grimes@csiro.au
      name: John Grimes
    name: pathling
    sources:
    - https://github.com/aehrc/pathling
    type: application
    urls:
    - https://pathling.csiro.au/helm/pathling-1.0.0.tgz
    version: 1.0.0
generated: "2024-01-11T07:09:04.462251265Z"
