apiVersion: v1
entries:
  pathling:
  - apiVersion: v2
    created: "2023-12-14T02:07:10.32272119Z"
    description: A Helm chart for Pathling Server
    digest: cce4f4b6df835c35569ae60b4aa35745a1ce3d4f321a24bc4484a3ad68be23c0
    icon: https://raw.githubusercontent.com/aehrc/pathling/main/media/logo-icon-colour-detail.svg
    keywords:
    - spark
    - analytics
    - standards
    - fhir
    - terminology
    maintainers:
    - email: John.Grimes@csiro.au
      name: John Grimes
    name: pathling
    sources:
    - https://github.com/aehrc/pathling
    type: application
    urls:
    - https://pathling.csiro.au/helm/pathling-1.0.0.tgz
    version: 1.0.0
generated: "2023-12-14T02:07:10.322194054Z"
