apiVersion: v1
entries:
  pathling:
  - apiVersion: v2
    created: "2024-03-17T08:38:10.240184171Z"
    description: A Helm chart for Pathling Server
    digest: 03093ca205893aa18eb55a022bd637926bf79af92687e23fec2c6cfbea1fa947
    icon: https://raw.githubusercontent.com/aehrc/pathling/main/media/logo-icon-colour-detail.svg
    keywords:
    - spark
    - analytics
    - standards
    - fhir
    - terminology
    maintainers:
    - email: John.Grimes@csiro.au
      name: John Grimes
    name: pathling
    sources:
    - https://github.com/aehrc/pathling
    type: application
    urls:
    - https://pathling.csiro.au/helm/pathling-1.0.0.tgz
    version: 1.0.0
generated: "2024-03-17T08:38:10.239450056Z"
