# Performs a benchmark and uploads the result for historical reporting.

name: Benchmark

on:
  push:
    branches:
      - benchmark-upload

jobs:
  benchmark:
    name: Benchmark
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::865780493209:role/PathlingBenchmarkUpload
          aws-region: ap-southeast-2
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          # This is required so that git-commit-id-plugin can find the latest tag.
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'zulu'
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |-
            ${{ runner.os }}-maven-
      - name: Cache test data
        id: cache-test-data
        uses: actions/cache@v2
        with:
          path: fhir-server/src/test/resources/test-data/parquet
          key: ${{ runner.os }}-test-data-${{ hashFiles('fhir-server/src/test/resources/test-data/fhir/*.ndjson', 'encoders/src/main/**/*.java', 'encoders/src/main/**/*.scala') }}
      - name: Run the verify goal with Maven
        env:
          # If there is a cache hit on the test data, we don't need to import it. If it is a cache
          # miss, we still need to explicitly activate the `importTestData` profile, otherwise
          # it will be deactivated by `skipTests`.
          PATHLING_PROFILES: runBenchmark,${{ steps.cache-test-data.outputs.cache-hit && '!importTestData' || 'importTestData' }}
        run: >-
          mvn --batch-mode verify
          -pl fhir-server -am
          -P${{ env.PATHLING_PROFILES }}
          -DskipSurefireTests -DskipScalaDocs
        timeout-minutes: 20
      - name: Upload benchmark artifact
        uses: actions/upload-artifact@v2
        with:
          name: benchmark-results
          path: "**/jmh-*.json"
      - name: Upload benchmark file to S3
        run: aws s3 cp **/jmh-*.json s3://pathling-benchmark/${{ github.ref }}/${{ github.run_id }}/${{ github.event.repository.updated_at }}.json
