# This workflow will build and test the server, and build the site.
# It will also package the server and the site up as Maven artefacts and Docker images, and push
# them to the configured repositories.
# This is only run on master, and is only intended for changes that have been reviewed and approved 
# for deployment.

name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.3
      - name: Run the deploy goal with Maven
        run: |
          mvn --batch-mode deploy \
          -Pdocker \
          -Dpathling.fhirServerDockerRepo=${{ secrets.FHIR_SERVER_DOCKER_REPO }} \
          -Dmaven.test.failure.ignore=true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        timeout-minutes: 30
      - name: Upload encoders test reports
        uses: actions/upload-artifact@v2
        with:
          name: encoders-surefire-reports
          path: encoders/target/surefire-reports
      - name: Upload fhir-server test reports
        uses: actions/upload-artifact@v2
        with:
          name: fhir-server-surefire-reports
          path: fhir-server/target/surefire-reports
      - name: Upload timing log
        uses: actions/upload-artifact@v2
        with:
          name: fhir-server-timing-log
          path: fhir-server/target/timing.log
      - name: Publish test results
        uses: scacap/action-surefire-report@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          check_name: Test report
          fail_on_test_failures: true
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: encoders/target/site/jacoco/jacoco.xml,fhir-server/target/site/jacoco/jacoco.xml
      - name: Tag and push server image
        run: |
          mvn dockerfile:tag@tag-major dockerfile:tag@tag-latest dockerfile:push@push-version \
          dockerfile:push@push-major dockerfile:push@push-latest -pl fhir-server \
          -Dpathling.fhirServerDockerRepo=${{ secrets.FHIR_SERVER_DOCKER_REPO }} \
          -Ddockerfile.username=${{ secrets.DOCKER_USERNAME }} \
          -Ddockerfile.password=${{ secrets.DOCKER_PASSWORD }}
