# This workflow will build the software and documentation to ensure there are no errors, and also
# execute the tests.
#
# This is run when pull requests are created and updated - it does not have any sort of privileged
# access.

name: Test PR

on: pull_request

# If the actor is Dependabot, we need to avoid anything that requires privileged access - so we skip
# the integration test (which requires a secret), and also the test reporting actions (which require
# a GitHub token).
jobs:
  encoders:
    name: Build and test encoders
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'zulu'
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Run the verify goal with Maven
        run: |
          mvn --batch-mode verify \
          -pl encoders -am
        timeout-minutes: 30
      - name: Upload encoders test reports
        uses: actions/upload-artifact@v2
        with:
          name: encoders-surefire-reports
          path: encoders/target/surefire-reports
  fhir-server:
    name: Build and test FHIR server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'zulu'
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Run the verify goal with Maven
        run: |
          mvn --batch-mode verify \
          -pl fhir-server -am \
          -Pdocker,skip-encoders-tests \
          -DskipITs
        timeout-minutes: 30
      - name: Upload fhir-server test reports
        uses: actions/upload-artifact@v2
        with:
          name: fhir-server-surefire-reports
          path: fhir-server/target/surefire-reports
      - name: Upload timing log
        uses: actions/upload-artifact@v2
        with:
          name: fhir-server-timing-log
          path: fhir-server/target/timing.log
  site:
    name: Build site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.3
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Run the verify goal with Maven
        run: |
          mvn --batch-mode verify \
          -pl site -am \
          -DskipTests
        timeout-minutes: 30
