# This workflow creates a pre-release Docker image.

name: Deploy pre-release Docker image

on:
  push:
    branches:
      - 'release/*'

jobs:
  deploy-docker:
    name: Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          # This is required so that git-commit-id-plugin can find the latest tag.
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'zulu'
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Run the deploy goal with Maven
        run: |
          TAG=$(echo '${{ github.ref }}' | sed 's/refs\/heads\/release\///')
          mvn --batch-mode deploy \
          -pl fhir-server -am \
          -PdockerPreRelease \
          -Dpathling.fhirServerDockerTag=$TAG \
          -DskipTests -DskipScalaDocs
        timeout-minutes: 30
