# This workflow packages up the pathling-client library, and publishes to NPM.
#
# This is only run when a version tag is pushed.

name: Release js/client

on:
  push:
    tags:
      - 'pathling-client-v**'

env:
  # The add-exports and add-opens flags are required for Java 17
  MAVEN_OPTS: --add-exports=java.base/sun.nio.ch=ALL-UNNAMED --add-exports=java.base/java.net=ALL-UNNAMED

jobs:
  deploy:
    name: NPM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # This is required so that git-commit-id-plugin can find the latest tag.
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'zulu'
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Run the deploy goal with Maven
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          mvn --batch-mode deploy \
          -pl lib/js -am \
          -PnpmPublish \
          -DskipTests
        timeout-minutes: 30
