# This workflow builds the documentation site, and deploys it to GitHub Pages.
#
# This is executed when a commit is pushed to the main branch.

name: Publish documentation site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and deploy documentation site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'zulu'
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Run the deploy goal with Maven
        env:
          GIT_USER: ${{ secrets.GIT_USER }}
          GIT_PASS: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mvn --batch-mode deploy \
          -pl site -am -DskipTests -Dmaven.deploy.skip
        timeout-minutes: 30
