# This workflow will test the server, and build the site to ensure there are no errors.
# This is run on branches other than master - it does not push or deploy anything.

name: Test

on:
  push:
    branches-ignore: [ master ]

jobs:
  test_server:
    name: Test server
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run the test goal with Maven
      run: mvn test -pl fhir-server -am
  test_site:
    name: Test site
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"
